"""Your migration message

Revision ID: aa2ba3cd2b87
Revises: 4074569b8e23
Create Date: 2025-04-23 11:49:44.179141

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa2ba3cd2b87'
down_revision = '4074569b8e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_detail_assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_detail_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_detail_id'], ['task_details.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('MANAGER', 'INTERN'),
               type_=sa.Enum('INTERN', 'MANAGER', name='userrole'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('INTERN', 'MANAGER', name='userrole'),
               type_=mysql.ENUM('MANAGER', 'INTERN'),
               existing_nullable=True)

    op.drop_table('task_detail_assignees')
    # ### end Alembic commands ###
